#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import json
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from optimizer.environment import collect_environment


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=Path("results"))
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = collect_environment()
    (args.output_dir / "environment.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    lines = [
        "# Environment Audit",
        "",
        "Generated by `scripts/detect_environment.py`.",
        "",
        f"- Mode: `{data['hardware_mode']}`",
        f"- OS: {data['operating_system']['system']} {data['operating_system']['release']}",
        f"- Python: `{data['python']['version']}`",
        f"- PyTorch: `{data['torch'].get('version', 'not installed')}`",
        f"- `torch.cuda.is_available()`: `{data['torch'].get('cuda_available', False)}`",
        f"- NVIDIA query: `{data['nvidia']['query'] or 'not available'}`",
        "",
    ]
    if data["hardware_mode"] != "cuda":
        lines.append("CUDA benchmark status: `NOT BENCHMARKED ON CURRENT HARDWARE`.")
    (args.output_dir / "environment.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()

