#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import json
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from optimizer.environment import collect_environment


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=Path("results"))
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = collect_environment()
    (args.output_dir / "environment.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    nvidia_devices = data["nvidia"].get("devices", [])
    nvidia_text = ", ".join(device.get("name", "unknown") for device in nvidia_devices)
    if not nvidia_text:
        nvidia_text = data["nvidia"].get("reason", "not available")
    adapters = data.get("display_adapters", [])
    adapter_text = ", ".join(adapter.get("name", "unknown") for adapter in adapters) or "not detected"
    lines = [
        "# Environment Audit",
        "",
        "Generated by `scripts/detect_environment.py`.",
        "",
        f"- Mode: `{data['hardware_mode']}`",
        f"- OS: {data['operating_system']['system']} {data['operating_system']['release']}",
        f"- Python: `{data['python']['version']}`",
        f"- PyTorch: `{data['torch'].get('version', 'not installed')}`",
        f"- `torch.cuda.is_available()`: `{data['torch'].get('cuda_available', False)}`",
        f"- CUDA workflow available: `{data.get('cuda_workflow_available', False)}`",
        f"- NVIDIA devices: `{nvidia_text}`",
        f"- Display adapters: `{adapter_text}`",
        f"- `nvcc`: `{data['toolchain'].get('nvcc') or 'not available'}`",
        f"- Nsight: `ncu={data['toolchain'].get('ncu') or 'not available'}`, `nsys={data['toolchain'].get('nsys') or 'not available'}`",
        "",
    ]
    if data["hardware_mode"] != "cuda":
        lines.append("CUDA benchmark status: `NOT BENCHMARKED ON CURRENT HARDWARE`.")
    (args.output_dir / "environment.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
